### PR TITLE
Fix numpy array and README example

### LINKED ISSUE #249: Errors with example calling Python from .NET
When trying to run the numpy example from the Readme file I see the following error:
TypeError : long() argument must be a string or a number, not '0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'

This seems to be cause by the Py.kw function call. However, the numpy.array does not seem to be working properly.  The console output looks like this:

image

This is from using the latest master branch and Python 2.7.  Has the array handling changed recently?

### PR DESCRIPTION
**Pull request by vmuriart**
### What does this implement/fix? Explain your changes.

Generic Lists were falling through and being classified as `typecode.Object`
To solve this, adding a specific processing branch for `Generic Lists` only
to avoid breaking the changes from 471673a1fa4691b3becb4d9fee6941308535bb04

### Does this close any currently open issues?

Closes #249

### Any other comments?

`n/a`

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)

### CODE REVIEW

File: src/runtime/converter.cs [hunk 1]
```diff
@@ -133,6 +134,16 @@ internal static IntPtr ToPython(object value, Type type)
                 return result;
             }
 
+            if (value is IList && value.GetType().IsGenericType)
+            {
+                var resultlist = new PyList();
+                foreach (object o in (IEnumerable)value)
+                {
```
Comment (denfromufa) [inline src/runtime/converter.cs]: @vmuriart can you make this consistent with this syntax in the same file? https://github.com/pythonnet/pythonnet/blob/423407a4e7ff783d8f4d9498eaa51bf8a12382ce/src/runtime/converter.cs#L214

Comment (vmuriart) [inline src/runtime/converter.cs]: Done.

File: src/runtime/converter.cs [hunk 2]
```diff
@@ -133,6 +134,22 @@ internal static IntPtr ToPython(object value, Type type)
                 return result;
             }
 
+            if (value is IList && value.GetType().IsGenericType)
+            {
```
Comment (denfromufa) [inline src/runtime/converter.cs]: To be completely consistent with the converter code the IEnumerable should be replaced with IList like you did this pull request.

The commit message mentioned that strings should not be converted to `PyList`. 

https://github.com/pythonnet/pythonnet/commit/471673a1fa4691b3becb4d9fee6941308535bb04

But `IEnumerable` is not quite right when converting to `PyList` anyway. `IList` is the closest interface like you selected. 
Other example which are IEnumerable, but not IList besides strings are HashSet, maybe even HashTable.

File: src/runtime/converter.cs [hunk 3]
```diff
@@ -133,6 +134,22 @@ internal static IntPtr ToPython(object value, Type type)
...
+                using (var resultlist = new PyList())
+                {
+                    foreach (object o in (IEnumerable)value)
```
Comment (vmuriart) [inline src/runtime/converter.cs]: @denfromufa are you talking about the `IEnumberable` here?

Comment (denfromufa) [inline src/runtime/converter.cs]: No, I meant this place:

https://github.com/pythonnet/pythonnet/blob/423407a4e7ff783d8f4d9498eaa51bf8a12382ce/src/runtime/converter.cs#L208

Comment (vmuriart) [inline src/runtime/converter.cs]: I left that alone on purpose as it wasn't necessary to modify for what this `pr` is trying to do. 

The correct thing there is probably to delete that section of code altogether though (or delete `typecode.Object`). The remaining typecodes are `Empty`, `DBNull`, `Decimal` and `DateTime` and i don't think any of those should be converted to `PyList`. 
Also, I can't think of a situation in which the `default` branch of the switch would be hit because we have `Typecode.Object` defined; It would always be called instead of the `default`. This [example](http://stackoverflow.com/a/7542810/5208670) is probably closer to how it should be written. 
Either way though, all those changes aren't needed for the purposes of fixing the `numpy arrays` which is why I didn't include them.

Comment (denfromufa) [inline src/runtime/converter.cs]: Agreed, I opened a separate issue for this dead code: https://github.com/pythonnet/pythonnet/issues/428

**Comment by vmuriart** [comment]
ok to merge then?

**Comment by denfromufa** [comment]
I'm not in the reviewers' list :) Can you mention this pull request on the original issue, if anyone wants to look at this?

**Comment by vmuriart** [comment]
not sure why you were removed. I added you originally, maybe it was removed after you submitted your review and I committed the fixes?

The original issue has a reference to this `pr` as well. The mention of #249 on the first comment created a link back to this one. Same w the commit

**Comment by denfromufa** [comment]
Yes, I think the review process can somehow remove the original reviewers. I can see 3 reviewers on the top.

The links you created in this pull request do not notify anyone on the original issue, because it is not a message in the issue tracker.

**Comment by vmuriart** [comment]
oh, i see what you're trying to do. you want them to review this `pr` if they have input on it right? Otherwise they should get the notification once the issue closes when this merges.
