### PR TITLE
Fix set pythonhome

### LINKED ISSUE #179: Incorrect marshalling of string in Py_SetPythonHome
I noticed that when `PythonEngine.PythonHome` was set and a subsequent `Initialize()` call was made my .Net application would close unexpectedly.

It looks like the call to `Py_SetPythonHome` made in runtime.cs is implicitly marshalling the string to a char array for the unmanaged code. My suspicion is that the Python sourcecode is keeping a record of the pointer rather than making a copy of the data. The managed runtime will free the memory allocated to char array as soon as the function finishes executing leaving a dangling pointer. This then leads to the unexpected `Initialize()` behaviour.

```
[DllImport(Runtime.dll, CallingConvention = CallingConvention.Cdecl,
    ExactSpelling = true, CharSet = CharSet.Ansi)]
internal unsafe static extern void
Py_SetPythonHome(string home);
```

The solution appears to be to explicitly marshal the string and hang onto the pointer until it is no longer needed, i.e.

```
[DllImport(Runtime.dll, CallingConvention = CallingConvention.Cdecl,
     ExactSpelling = true, CharSet = CharSet.Ansi)]
internal unsafe static extern void
Py_SetPythonHome(IntPtr home);
```

```
IntPtr str = Marshal.StringToHGlobalAnsi(@"C:\Python27");
Py_SetPythonHome(str);
// do stuff
Marshal.FreeHGlobal(str);
```

Running Win7, .Net4.5 and Python 2.7.11.

### PR DESCRIPTION
**Pull request by vmuriart**
### What does this implement/fix? Explain your changes.

Fixes setters for `PythonEngine.PythonHome` `PythonEngine.ProgramName` and `PythonEngine.PythonPath`. 

It extends #279/#186: 
- Fix the issue in Python 2/3 and 32/64bit
- Fix memory leak on multiple `setters`

### Does this close any currently open issues?

Closes #179
Closes #279 (replaces)
Closes #186 (replaces)

### Any other comments?

There's quite a bit of repeated code on this `pr`. I'll perform the clean-up after this `pr` is merged to avoid obscuring how this is being fixed. 

`PythonEngine.PythonPath`, is misleading since it doesn't directly map to `PYTHONPATH` and should be called `Path` instead. `py_set_path` doesn't exist on `PY27` but it was erroneously defined at some point. 
Needs to be removed, but its outside the scope of this `PR`. 

### Checklist

Check all those that are applicable and complete.

-   [x] Make sure to include one or more tests for your change
-   [x] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)

### CODE REVIEW

**Comment by vmuriart** [comment]
miniconda failures seem to be due to some update to the pre-installed ones. Not related to this pr.

**Comment by denfromufa** [comment]
@vmuriart I don't see miniconda failures?

File: src/runtime/pythonengine.cs [hunk 1]
```diff
@@ -64,7 +67,17 @@ public static string ProgramName
 
                 return result ?? "";
             }
-            set { Runtime.Py_SetProgramName(value); }
+            set
+            {
+                if (_programName != IntPtr.Zero)
```
Comment (denfromufa) [inline src/runtime/pythonengine.cs]: the check for IntPtr.Zero is not necessary

**Comment by vmuriart** [comment]
Already fixed the miniconda fails.

File: src/runtime/pythonengine.cs [hunk 2]
```diff
@@ -64,7 +67,17 @@ public static string ProgramName
...
+                {
+                    Marshal.FreeHGlobal(_programName);
+                }
+                _programName = Runtime.IsPython3
+                    ? UcsMarshaler.GetInstance("").MarshalManagedToNative(value)
```
Comment (denfromufa) [inline src/runtime/pythonengine.cs]: 2 custom marshalling articles suggest that GetInstance should be a singleton like this:

```
public static ICustomMarshaler GetInstance(string cookie)
   {
       if (marshaler == null)
       {
              marshaler = new UcsMarshaler();
       }
       return marshaler;
   }
```

File: src/runtime/pythonengine.cs (hunk 1 above)
Comment (vmuriart) [inline src/runtime/pythonengine.cs]: What would you replace it with? Without it, we'd end up trying to `dealloc` null

File: src/runtime/pythonengine.cs (hunk 2 above)
Comment (denfromufa) [inline src/runtime/pythonengine.cs]: and this SO Q/A confirms: http://stackoverflow.com/q/18498452/2230844

Comment (vmuriart) [inline src/runtime/pythonengine.cs]: it is already. https://github.com/pythonnet/pythonnet/blob/0a478024175e52106d9d4ff2230e1f505e56d7d8/src/runtime/CustomMarshaler.cs#L166

Comment (denfromufa) [inline src/runtime/pythonengine.cs]: oh, sorry, missed that!

Comment (vmuriart) [inline src/runtime/pythonengine.cs]: No worries. I almost went w that implementation

File: src/runtime/pythonengine.cs (hunk 1 above)
Comment (denfromufa) [inline src/runtime/pythonengine.cs]: according to docs this is fine: https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.freehglobal(v=vs.110).aspx#Anchor_1

Comment (vmuriart) [inline src/runtime/pythonengine.cs]: ok makes sense. My original implementation `dealloc` twice. A better check would have been to check against `null`. Ill fix it up

**Comment by denfromufa** [comment]
@vmuriart this pull request adds @leomeuk as contributor, so can you add him? @leomeuk do you agree to transition from Zope to MIT? Your original pull request was made under the old Zope license.

**Comment by vmuriart** [comment]
I forgot about that. @leomeuk hasn't been active since he opened the original `pr`. Note that all his contributions survived in the end.
