### PR TITLE
 #2240 Recursion error when doing reversed python operations on C# types

### LINKED ISSUE #2240: RecursionError when substracting System Decimal from Python Decimal
### Environment

-   Pythonnet version: Version: 3.0.1
-   Python version: 3.10
-   Operating System: Any (Windows/Linux)
-   .NET Runtime: 6.0.0

### Details

-   Trying to substract System Decimal from Python Decimal (the other way works fine)

    _TODO_

- import both system decimal and python decimal
- create a separate variable from each type
- subtract System Decimal from Python Decimal

```python
    from System import Decimal as SysDecimal
    from decimal import Decimal as PyDecimal
    sys_dec = SysDecimal(1)
    py_dec = PyDecimal(1)
    print(str(sys_dec - py_dec )) # works fine
    print(str(py_dec - sys_dec)) # crashes
```

-   error thrown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RecursionError: maximum recursion depth exceeded while calling a Python object

### PR DESCRIPTION
**Pull request by gertdreyer**
### What does this fix? Explain your changes.

Reverse operators were not implemented correctly for C# types which resulted in Recursion errors when embedding C# in Python. Changed the model binding process to add reverse operators for all applicable types. Added a flag to MethodBinder that signals the operation is a reversed operation and that the arguments to the operator needs to be reversed.

Added tests and an wrapper object for int without overloaded operator methods and a wrapper codec to test the reverse operations (and forward operator on the same type for safety).
...

### Does this close any currently open issues?
This should resolve #2240.
...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

-   [X] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Ensure you have signed the [.NET Foundation CLA](https://cla.dotnetfoundation.org/pythonnet/pythonnet)
-   [X] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [X] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

File: src/embed_tests/TestOperator.cs [hunk 1]
```diff
@@ -23,6 +24,120 @@ public void Dispose()
             PythonEngine.Shutdown();
         }
 
+        // Mock Integer class to test math ops on non-native dotnet types
+        public struct OwnInt
```
Comment (lostmsu) [inline src/embed_tests/TestOperator.cs:28]: I know this is test code, but please override `Equals` and `GetHashCode` to clear the warning.

File: src/embed_tests/TestOperator.cs [hunk 2]
```diff
@@ -23,6 +24,120 @@ public void Dispose()
...
+            {
+                PyObjectConversions.RegisterDecoder(new OwnIntCodec());
+            }
+
+            public bool CanDecode(PyType objectType, Type targetType)
+            {
+                return objectType.Name == "int" && targetType == typeof(OwnInt);
+            }
+
+            public bool TryDecode<T>(PyObject pyObj, out T? value)
```
Comment (lostmsu) [inline src/embed_tests/TestOperator.cs:128]: Please add `#nullable enable` to the file and fix the warnings or remove this nullable annotation.

File: src/embed_tests/TestOperator.cs [hunk 3]
```diff
@@ -23,6 +24,120 @@ public void Dispose()
...
+            {
+                if (pyObj.PyType.Name != "int" || typeof(T) != typeof(OwnInt))
```
Comment (lostmsu) [inline src/embed_tests/TestOperator.cs:130]: I don't think you need this check.

File: src/runtime/MethodBinder.cs [hunk 4]
```diff
@@ -363,10 +371,10 @@ public MismatchedMethod(Exception exception, MethodBase mb)
                 _methods = GetMethods();
             }
 
-            return Bind(inst, args, kwargDict, _methods, matchGenerics: true);
+            return Bind(inst, args, kwargDict, _methods, matchGenerics: true, reverse_args);
         }
 
-        static Binding? Bind(BorrowedReference inst, BorrowedReference args, Dictionary<string, PyObject> kwargDict, MethodBase[] methods, bool matchGenerics)
+        private static Binding? Bind(BorrowedReference inst, BorrowedReference args, Dictionary<string, PyObject> kwargDict, MethodBase[] methods, bool matchGenerics, bool reversed = false)
```
Comment (lostmsu) [inline src/runtime/MethodBinder.cs:377]: naming: it is unclear what is reversed. Should be `argsReversed`

File: src/runtime/MethodBinder.cs [hunk 5]
```diff
@@ -28,17 +28,22 @@ internal class MethodBinder
...
         [NonSerialized]
         public bool init = false;
+
         public const bool DefaultAllowThreads = true;
         public bool allow_threads = DefaultAllowThreads;
 
-        internal MethodBinder()
+        public bool args_reversed = false;
+
+        internal MethodBinder(bool reverse_args = false)
```
Comment (lostmsu) [inline src/runtime/MethodBinder.cs:37]: naming: here and in other places the parameter should be `reverseArgs`

**Review by lostmsu — COMMENTED** [review]
Can you explain what caused the issue was (e.g. what caused the error) and how this fix addresses this scenario?

**Comment by gertdreyer** [comment]
Changes made...

I traced it down to the nb_add, nb_mul, etc slots only having the forward operators defined/linked for C# types being used in Python, this somehow caused the RecursionError when any reverse operators are called as they are probably just pointing to random pointers. 

`py * cs` calls `py.__mul__(cs)` which is returns not implemented for the cs type and codecs does not get called prior to the __mul__ call which results in `cs.__rmul__(py)` being called which caused the recursion error. I do not believe that there are problems with the codec system but it is needed to test this due to being on both sides of the CLR boundary.

It seems there were only catered for forward operators when both are the different (with overloaded operators, i.e. OwnInt - Int64 and Int64 - OwnInt). Thus all the code to detect whether a call is a reverse operator tested based on calling and passed types. Thus when called with the same types it could never detect it was a reversed operation even if it were defined.  This needed some changes to the MethodBinding and ModelBinding to ensure the reversed calls are linked to the right C# operators and called with the arguments swapped.

File: src/runtime/MethodBinder.cs [hunk 6]
```diff
@@ -28,17 +28,22 @@ internal class MethodBinder
...
+        public bool argsReversed = false;
+
+        internal MethodBinder(bool argsReversed = false)
         {
             list = new List<MaybeMethodBase>();
+            this.argsReversed = argsReversed;
         }
 
-        internal MethodBinder(MethodInfo mi)
+        internal MethodBinder(MethodInfo mi, bool argsReversed = false)
```
Comment (lostmsu) [inline src/runtime/MethodBinder.cs:43]: IMHO, you don't need this parameter in constructor. Just set the field directly when needed.

E.g. `new MethodBinder(...) { argsReversed = true }`

File: src/runtime/MethodBinder.cs [hunk 7]
```diff
@@ -271,10 +276,11 @@ internal static int ArgPrecedence(Type t)
         /// <param name="inst">The Python target of the method invocation.</param>
         /// <param name="args">The Python arguments.</param>
         /// <param name="kw">The Python keyword arguments.</param>
+        /// <param name="argsReversed">Reverse arguments of methods. Used for methods such as __radd__, __rsub__, __rmod__ etc</param>
         /// <returns>A Binding if successful.  Otherwise null.</returns>
-        internal Binding? Bind(BorrowedReference inst, BorrowedReference args, BorrowedReference kw)
+        internal Binding? Bind(BorrowedReference inst, BorrowedReference args, BorrowedReference kw, bool argsReversed = false)
```
Comment (lostmsu) [inline src/runtime/MethodBinder.cs:281]: Do you need to pass this parameter at all? Don't you have the field?

Comment (gertdreyer) [reply src/runtime/MethodBinder.cs]: Cleaned it up a bit. I missed that... The one method is static though so we will need to still pass it there...

**Review by lostmsu — APPROVED** [review]
