### PR TITLE
Ensure only implementers of IEnumerable or IEnumerator are considered Iterable

### LINKED ISSUE #1234: .NET class instances considered Iterable
### Environment

-   Pythonnet version: 2.5.0
-   Python version: 3.7
-   Operating System: Windows

### Details

All .NET class instances are considered instances of `collections.abc.Iterable`.

```C#

namespace Python.Test {
  public class Empty { }
}
```

```python

def test_not_Iterable():
    """Test regular .NET objects are not iterable"""
    from Python.Test import Empty
    from collections.abc import Iterable

    assert (not isinstance(Empty(), Iterable))
```

The test is expected to pass, but fails:

```
    def test_not_Iterable():
        """Test regular .NET objects are not iterable"""
        from Python.Test import Empty
        from collections.abc import Iterable

>       assert (not isinstance(Empty(), Iterable))
E       AssertionError: assert not True
E        +  where True = isinstance(<Python.Test.Empty object at 0x0000022D3E6DE5C8>, <class 'collections.abc.Iterable'>)
E        +    where <Python.Test.Empty object at 0x0000022D3E6DE5C8> = <class 'Python.Test.Empty'>()
```

### PR DESCRIPTION
**Pull request by danabr**
### Does this close any currently open issues?

Fixes #1234.

### Checklist

Check all those that are applicable and complete.

-   [X] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [X] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [X] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Review by filmor — APPROVED** [review]
Thank you very much, looks good to me.

@lostmsu Can you have a look as well?

Mid-term we should probably just fill the slots explicitly instead of picking up methods by name.

File: src/runtime/typemanager.cs [hunk 1]
```diff
@@ -713,6 +713,13 @@ internal static void InitializeSlots(IntPtr type, Type impl)
                         continue;
                     }
 
+                    if (name == "tp_iter" && clrType != null &&
+                        !clrType.GetInterfaces().Any(i => i == typeof(IEnumerable) || i == typeof(IEnumerator)))
+                    {
+                        continue;
+                    }
+
+
```
Comment (lostmsu) [inline src/runtime/typemanager.cs:722]: This logic should be in the caller (I guess `CreateType` in this case), and `tp_iter` should be either be made private to not be handled by generic code here, or the slot should be overwritten after `InitializeSlots` is called.

A few reasons:
1) different slots might require different information to figure out if and how they need to be initialized. If in the future we would need to add custom initialization for a different method, the parameter list of this function would grow.
2) if each slot will require own handling, this method would grow too.

**Review by lostmsu — CHANGES_REQUESTED** [review]

File: src/runtime/typemanager.cs (hunk 1 above)
Comment (danabr) [reply src/runtime/typemanager.cs]: Yes, my first approach was too hackish.

I went with the second approach of overwriting the slot after `InitializrSlots`. For some reason, I couldn't get moving the handling of tp_iter out of the generic code to work.

Comment (lostmsu) [reply src/runtime/typemanager.cs]: @danabr its because it is already hackish, as it simply matches public methods to slots by name. I hope we will get rid of it...

**Review by lostmsu — APPROVED** [review]

**Comment by lostmsu** [comment]
Thanks for the contribution!
